### ISSUE TITLE
Is there any difference between groom-nms and penalize highest-confidence proposal using gt directly?

### ISSUE THREAD

**Issue by kaixinbear** [abhi1kumar/groomed_nms#1]
Hi~thanks for your great work.
However, I have some confusion in understanding the motivation of this algorithm. 
If we want to achieve the consistency of training and test, we can simply penalize the highest-confidence proposal in the training pipeline, which seems to achieve similar result.So, is there any difference between groom-nms and penalize highest-confidence proposal using gt directly?

**Comment by abhi1kumar** [comment]
@kaixinbear Thank you for showing interest in our work. As explained in the Introduction (Page 1) of our [paper](https://arxiv.org/pdf/2103.17202.pdf), the motivation of using NMS in training is two-fold :

- Address the mismatch between training and inference pipelines.
- Improve the localization and score of the box proposals.

Another motivation of our work is to get a simple closed-form mathematical NMS.

Unfortunately, I am not aware of any such work. Therefore, would you mind pointing to the paper which shows that penalizing the highest-confidence proposal in the training pipeline is equivalent to doing an NMS?

By the way, GrooMeD-NMS does **NOT** always penalize the highest score/confidence box proposals. If the highest confidence proposal is the _best_-localized box proposal for an object, it does not reduce its confidence. However, suppose there is another box proposal that is better localized than the highest confidence box proposal. In that case, GrooMeD-NMS provides a gradient to reduce the confidence of the highest confidence box proposal and provides another gradient to increase the confidence of the lower confidence (better localized) box proposal.

**Comment by kaixinbear** [comment]
Thanks for your reply and I highly appreciate your effort in formulating a  closed-form mathematical NMS.

I haven't read the paper that penalizing the highest-confidence proposal in the training pipeline, which is just my intuitive idea that does the similar thing as GrooMeD-NMS from the perspective of gradient.

To be honest, my math is not good enough to fully understand the GrooMeD-NMS. 

Would you mind tell me whether it would achieve similar result as GrooMeD-NMS if I  penalize the cls and regression of both highest-confidence box proposal and best-localized box proposal simultaneously ?

**Comment by abhi1kumar** [comment]
I am not fully sure but my hunch is that your penalization scheme would not work.
