### ISSUE TITLE
NMS on 2D boxes 

### ISSUE THREAD

**Issue by stencilman** [abhi1kumar/groomed_nms#2]
Can this be used as is or after any modifications for NMS on 2D bounding boxes?

**Comment by abhi1kumar** [comment]
@stencilman GrooMeD-NMS can be used as it is in inference. However, while training for 2D Object Detection, the target/best box definition needs to be modified. Our best box for 3D Object Detection uses product of both IoU2D and gIoU3D (Equation 9 of our [paper](https://arxiv.org/pdf/2103.17202.pdf)). The best box for 2D Object Detection uses only IoU2D (Equation 13 of [65] [paper](http://www.nowozin.net/sebastian/papers/prokudin2017objectdetections.pdf)).

[65] Prokudin et al, Learning to filter object detections.  GCPR, 2017.

**Comment by stencilman** [comment]
Thank you!
