### ISSUE TITLE
Problem in test

### ISSUE THREAD

**Issue by chenH20000109** [abhi1kumar/groomed_nms#4]
Hi, this is an exciting work.And i have a question when I try to test with the pre-train model. I can't find "Kinematic3D-Release/val1_kinematic/model_final".

**Comment by abhi1kumar** [comment]
Hi @chenH20000109 
I believe you are using the Kinematic3D repo file [scripts/scripts/test_rpn_3d.py](https://github.com/abhi1kumar/groomed_nms/blob/main/scripts/test_rpn_3d.py) for testing. I use the [scripts/train_rpn_3d.py](https://github.com/abhi1kumar/groomed_nms/blob/main/scripts/train_rpn_3d.py) (the one used for training) for testing as well.

The correct code for running the evaluation is [scripts_evaluation.sh](https://github.com/abhi1kumar/groomed_nms/blob/main/scripts_evaluation.sh) and uses [scripts/train_rpn_3d.py](https://github.com/abhi1kumar/groomed_nms/blob/main/scripts/train_rpn_3d.py) with the `--test` argument. You should use
```
CUDA_VISIBLE_DEVICES=0 python -u scripts/train_rpn_3d.py --config=groumd_nms        --restore=50000 --test
```
